[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "thunder"
version = "0.0.0"
authors = [{ name = "ecstayalive", email = "ecstayalive@163.com" }]
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "numpy",
    "gymnasium",
    "wandb",
    "tqdm",
    "rich",
    "rich_argparse",
    "pytest",
    "tyro",
]


[project.urls]
"Homepage" = "https://github.com/ecstayalive/thunder"
"Bug Tracker" = "https://github.com/ecstayalive/thunder/issues"

[project.scripts]

[project.optional-dependencies]
torch = ["torch>=2.0.0", "mamba-ssm"]
jax = ["jax>=0.4.0", "jaxlib>=0.4.0", "flax>=0.7.0", "optax>=0.1.7"]
warp = ["warp-lang"]
all = ["thunder[torch,jax]"]
